spring:
  application:
    name: practice-flink
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  kafka:
    input-topic: orders
    output-topic: enriched-orders
    stats-topic: user-order-stats
    windows-topic: user-order-windows
  flink:
    checkpoint-dir: file:///tmp/practice-flink-checkpoints
